[package]
name = "tech_scan"
description = "A tool for analyzing and visualizing technology stacks in codes."
version = "0.1.0"
edition = "2024"

[lib]
name = "tech_scan"
path = "src/lib.rs"

[[bin]]
name = "tech-scan"
path = "src/main.rs"

[dependencies]
clap = {version = "4.5.43", features = ["derive"]}
ignore = "0.4.23"
