[package]
name = "tech_scan"
description = "A tool for analyzing and visualizing technology stacks in codes."
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[lib]
name = "tech_scan"
path = "src/lib.rs"

[[bin]]
name = "tech-scan"
path = "src/main.rs"

[dependencies]
clap = {version = "4.5.43", features = ["derive"]}
config = "0.15.14"
ignore = "0.4.23"
serde = {version = "1.0", features = ["derive"]}
