[package]
name = "tech-scan"
description = "A tool for analyzing and visualizing technology stacks in codes."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.43", features = ["derive"]}
walkdir = "2.5.0"
